### ISSUE TITLE
User should be able to manually enter "contact email" field on feedback form

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-feedback#16]
As a Feedback user, I want to be able to manually enter in a contact email.

### Acceptance Criteria
1. Verify that the Contact Email field is above the main contact field for the Feedback form.
1. Verify that the email is saved on the Feedback. (This may require #6 for verification)

@shanear @lakohl — @shellicious pointed out that many ROs seem to use shared logins for certification. In light of that fact, do you think that we should capture both the username coming in and allow users to optionally enter a contact email? 

### Sub-Tasks

- [ ] QA discovery and scripting.

**Comment by amprokop** [comment]
@shanear @lakohl — thoughts?

**Comment by shanear** [comment]
@amprokop Accommodating shared CSS logins is a dangerous game, because that affects a lot of other situations where we are assuming 1 CSS login = 1 person. I think we should continue to operate under this assumption, and use whatever email is associated with the CSS account. This will further put pressure on folks to use 1 CSS account.

**Comment by amprokop** [comment]
@shanear — i totally understand the desire to have users use their own accounts rather than shared ones. Not sure exactly how much leaving out a "Contact info" form field would put pressure on them to do so though. Seems to me like it might just make things harder for our support staff trying to contact them. Will leave this aside for now and return to it if it becomes an issue though.

**Comment by shanear** [comment]
@amprokop good point. A phone # is sometimes useful for contacting them. Also, if there is a discrepancy in email addresses, we can tell them to fix that in addition to contacting them about their feedback lol.

We should let @shellicious make the call here.

**Comment by msknee** [comment]
I was chatting with @Chingujo about this and we both agree that having an email address field is the right call. Phone numbers are a little tricky, since I've been given the general regional office phone # recently. Email seems like the fastest way to understand the specific person giving the feedback, and a way to reach them afterwards. And if we know their email, we can help them set up a personal account for Caseflow. 

cc @amprokop @shanear

**Comment by shanear** [comment]
@shellicious should we have the email field default to their account email?
