### ISSUE TITLE
Button to return from confirmation page

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-feedback#2]
When I see the confirmation page, I should be able to go back to the application I was redirected from so I can continue my work.
- [ ] Create a button at the bottom of the confirmation page that goes back to the app the user was redirected from

![image](https://cloud.githubusercontent.com/assets/6335546/19771263/52b9fc60-9c30-11e6-8dd1-f02fb4cc70f7.png)

**Comment by amprokop** [comment]
Fixed. Closing.

**Comment by shanear** [comment]
@amprokop can you help alexis validate this?

**Comment by astewarttistatech** [comment]
The button wording is off as well as color. I need someone to approve these changes @shanear 

Please see attached.
<img width="616" alt="screen shot 2016-12-02 at 3 00 01 pm" src="https://cloud.githubusercontent.com/assets/23038505/20848529/7ee1063a-b8a0-11e6-99d4-28224afcea83.png">

**Comment by amprokop** [comment]
@astewarttistatech — The mock was in black and white because it was an early version.  The colors are correct (you'll see that they match the other mocks).

As for the wording, we display the name of the topic that the user is giving feedback for. Did you arrive at the Caseflow Feedback app by clicking a link from Caseflow Dispatch (URLs like "/dispatch/*"? If so, then you should see "Caseflow Dispatch" displayed in the feedback app. If you arrive from eFolder Express, it will display eFolder Express, and if you arrive from Caseflow Certification (URLs like "/certifications/*"), you will see "Caseflow Certification". If you navigate directly to the Feedback URL without passing information in a querystring, it will just display "Caseflow".

Can you revalidate with this in mind? Let me know if you have any questions.

**Comment by shanear** [comment]
@astewarttistatech The colors are good, they match the most recent mocks. The button will change based on the original application. Those things are good! We can close this out.
