### ISSUE TITLE
Admin | Dashboard | Ability to search

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-feedback#69]
As a Product Support Analyst, I want a dynamic search to easily search for Feedback items in the Dashboard section of the Feedback Admin page so that I can quickly view and manage relevant Feedback items.

# Acceptance Criteria 
1. Verify that the Feedback item data can be searched by all associated data elements. 
1. Verify that on the Feedback Admin page, the _"Search"_ bar allows for entering search criteria relevant to the following data elements about a Feedback item:  
    - User Email
    - Application
    - Date
    - Github Issue
    - PII
1. Verify that the _"Search"_ bar allows for Typeahead searching (values are filtered as you type). (Refer to Mockup)
1. Verify that the _"Search"_ bar allows for wild card searching using "*" as the wild card.
1. Verify that after clicking on the **_Search_** icon, the Feedback items that match the search criteria is displayed in the Dashboard section.   
1. Verify that after entering search criteria and pressing the Enter key, the search is executed and displays the matching feedback items in the Dashboard.

# Mockups 

![caseflow feedback admin](https://cloud.githubusercontent.com/assets/23316107/22375238/3760a2fe-e477-11e6-9f0a-4a270554c446.png)

**_View - Feedback Admin page - Searching on User email with type-ahead feature_**
![name search](https://cloud.githubusercontent.com/assets/23316107/22339996/e69603a4-e3b9-11e6-837f-27e3ada181d0.png)

**_View - Feedback Admin page - Searching on Github Issue number_**
![name search](https://cloud.githubusercontent.com/assets/23316107/22339934/b3bcd3ae-e3b9-11e6-9ea0-7a8c8b799eb8.png)

# Related Stories 
Caseflow Feedback | Create Engineering stories to Modify UI and functionality [#1767](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1767)
Epic: Feedback Admin View: Ability to view and report incoming feedback form Caseflow - [#1050](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1050)

**Comment by nikitarockz** [comment]
# My Feedback
### Sections with Suggested Changes
The following sections with a check mark are those I have suggested changes.  I have also indicated if done already or where to find my suggestions.

- [X] Title - Done
- [X] User Story - refer to Changes section
- [X] Acceptance Criteria - Refer to changes section
- [X] Mockup - @Chingujo needs updating
- [ ] Related Stories

### Comments
n/a
### Questions
Can you do wild card searching, ie. *jones, 12*, etc. ?

### Changes
As a Product Support Analyst, I want a dynamic search to easily search for Feedback items in the Dashboard section of the Feedback Admin page so that I can  quickly view and manage relevant Feedback items. 

# Acceptance Criteria 
1. Verify that the Feedback item data can be searched by all associated data elements. 
1. Verify that on the Feedback Admin page, the _"Search"_ bar allows for entering search criteria relevant to the following data elements about a Feedback item:  
    - Status
    - User Email
    - Application
    - Date
    - Github Iissue Number
1. Verify that the _"Search"_ bar allows for Typeahead searching (values are filtered as you type). (Refer to Mockup)
1. Verify that after clicking on the **_Search_** icon, the Feedback items that match the search criteria is displayed in the Dashboard section.   
1. Verify that after entering search criteria and pressing the Enter key, the search is executed.

### Mockups
1. For the 1st image, can you snip away some of the empty gray space.  I to try to use a little space as necessary to prevent so much scrolling to see the main information.   
1. Update the heading of the images to the following:
**_View - Feedback Admin page - Searching on User email with type-ahead feature_**
**_View - Feedback Admin page - Searching on Github Issue number_**
**_View - Feedback Admin page - Searching on Status_**

**Comment by nikitarockz** [comment]
Moving this out of icebox and placing it into Read-for-Dev.  Now that the Support Team must go into the Feedback to get the details of every single ticket, they really need to be able to search considering the amount of tickets that are on the dashboard.  Clicking Next to go through each page to find an issue is unacceptable.

**Comment by nemodjuric** [comment]
@Chingujo @nikitarockz We have PII column now, do we need this in search? If so, please add it to the description.

**Comment by nikitarockz** [comment]
@nemodjuric Thanks for pii.  Yes we need the search.

**Comment by nikitarockz** [comment]
Oh.  You mean do we need to be able to search for pii us the new search field.  I am going to say no to that.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
