### ISSUE TITLE
Slack: Appeals-Support: Caseflow Feedback Bot: Add github link in notification

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-feedback#72]
As Product Support Analyst, I would like to have the Feedback Slack notification that is sent to the Appeals-Support channel to include a link to the github issue so that I can easily click on it an view the issue in github.

# Acceptance Criteria 
1. Verify that the following links are in the notification:  **_Github, Admin Dashboard_**
1. Verify that slack notification is the following:

     > New feedback was submitted about [Application Product Name].  View it in **_Github_** or **_Admin Dashboard._**
1. Verify that after clicking on the Github link, the issue is displayed in a new web browser tab.
1. Verify that after clicking on the Admin Dashboard, the Admin Feedback dashboard is displayed via the following URL (Note: Must login first.):  
https://feedback.cf.ds.va.gov/admin/

# Mockup
**_View - Feedback Slack Notification - Before_**
![image](https://cloud.githubusercontent.com/assets/23063044/22037604/d969e524-dcc5-11e6-9b7e-f2f8a837dff9.png)

**_View - Feedback Slack Notification - After_**
![image](https://cloud.githubusercontent.com/assets/23063044/22071484/4f8994d2-dd6d-11e6-8f26-fb21d18d4643.png)

# Related Stories 
Epic: Feedback Admin View: Ability to view and report incoming feedback form Caseflow - [#1050](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1050)

**Comment by nikitarockz** [comment]
# My Feedback
### Sections with Suggested Changes
- [X] Title - Done
- [X] User Story - refer to Changes
- [X] Acceptance Criteria - Refer to changes
- [X] Mockup - @Chingujo needs updating
- [ ] Related Stories

### Comments
You know what?  I don't think we need this one because it is covered in #78.  Let's re-purpose this one for the Username Menu story.

### Questions
n/a

### Changes

**Comment by anyakhvost** [comment]
This can only be tested in UAT (as long as SLACK_WEBHOOK_URL is defined)

**Comment by astewarttistatech** [comment]
**PASSED**

Steps to Validate:

1. Go to feedback and create an issue in PROD
2. Go to the admin page of feedback in prod to see if the issue was created. 
3. Check Slack channel, _Appeals-support_ , to see if a notification was generated. 

Screenshot:

<img width="784" alt="screen shot 2017-01-26 at 11 48 09 am" src="https://cloud.githubusercontent.com/assets/23038505/22341157/c3c35274-e3bd-11e6-9e7e-ea53ebc2b311.png">

<img width="1201" alt="screen shot 2017-01-26 at 11 52 13 am" src="https://cloud.githubusercontent.com/assets/23038505/22341215/0494f1ae-e3be-11e6-966e-9179845f1e7e.png">
