### ISSUE TITLE
Admin | Footer | Contains extra formatting and punctuation marks and extended footer

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-feedback#77]
# Description
The current footer has extra formatting and punctuation marks that need to be removed.  Secondly, the heart and "VA" should not be underlined.  There also shouldn't be a period at the end of "VA".  Finally, the footer line is extended beyond the app canvas main content.

**Environment:**
- [x] Production
- [ ] UAT
- [x] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [X] Design
- [ ] Security
- [ ] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [ ]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
1. Log in to the Admin Feedback page.
1. Look at the footer on the page. 

## Screenshots
**_View - Admin Feedback page - Incorrect Footer_**
![image](https://cloud.githubusercontent.com/assets/23063044/22309850/0e3aa882-e31b-11e6-9de6-f0176314d190.png)

View - Admin Feedback page - Correct Footer
![caseflow feedback admin](https://cloud.githubusercontent.com/assets/23316107/22336373/05d60688-e3b0-11e6-8bc3-992dd7b08fd0.png)

# Related Issues
n/a

**Comment by nikitarockz** [comment]
Still working on this one.......
As a product support team member, I want to be able to easily see and respond to incoming feedback in a dashboard table so that I can can effectively respond and report important issues and feature requests.

1. Verify that after navigating to the Admin Feedback page, there is a Dashboard table with the following columns:
   - User
   - Date
   - Application
   - Status
   - Github Issue
1. Verify that the initial data set view only displays feedback form items with a _"Status'_ of "Under Review" 
1. Verify that for each Feedback Form item the appropriate data is displayed for the following columns:
   - User:   The submitter's va.gov email address
   - Date:  The date the form was submitted using the following format:  MM/DD/YY
   - Application:  The name of the application from which the feedback was submitted. 
   - "Status": Under Review or Completed
   - "Github Issue": Related Github issue number 
1. Verify that there is a search bar on the upper right of the App Canvas 
1. Verify that there is a link called "View Feedback >>" on the right of the Github Issue

**Comment by shanear** [comment]
This is a styleguide issue, it should be fixed in Caseflow Commons

**Comment by mmlumba** [comment]
Also this is fixed in this PR (which fails due to `pdftk` not working for some reason): https://github.com/department-of-veterans-affairs/caseflow-feedback/pull/113

**Comment by gnakm** [comment]
@Chingujo I added your correct footer mock in the styleguide footer issue https://github.com/department-of-veterans-affairs/caseflow/issues/1090

**Comment by Chingujo** [comment]
Thank you @gnakm. Closing in favor of the above issue.
