### ISSUE TITLE
User | Feedback Form | Send Feedback | Change Application Name values for Certification and outside application

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-feedback#78]
As a Product Support Analyst, I would like the value of the Application Name for Certification changed to "Certification" so that it more accurately reflects the specific application.

# Acceptance Criteria 
1. Verify that after clicking the **_Send Feedback_** button on the User Feedback page from the Certification product, the "Application Name" value is set to "Certification". (Note:  Can be seen on the Admin Feedback page.)

# Mockups 
**_View - User Feedback page from Certification_**
![image](https://cloud.githubusercontent.com/assets/23063044/22360703/30d4bd82-e420-11e6-8a72-48bf40ba377a.png)

**_View - User Feedback page from direct access_**
![image](https://cloud.githubusercontent.com/assets/23063044/22360716/5edde7bc-e420-11e6-90af-6591cfbf26d4.png)

# Related Stories
Epic: Feedback Admin View: Ability to view and report incoming feedback form Caseflow [#1050](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1050#issuecomment-266861719)

**Comment by nikitarockz** [comment]
# My Feedback
### Sections with Suggested Changes
- [X] Title - Done
- [X] User Story - refer to Changes
- [X] Acceptance Criteria - Refer to changes
- [X] Mockup - @Chingujo needs updating
- [ ] Related Stories

### Comments
n/a
### Questions
n/a

### Changes
As a Product Support Analyst, I want to be able to see feedback details in a modal view so that I can quickly read through important information and respond as necessary with the least amount of clicks.

# Acceptance Criteria 
1. Verify that the Feedback Detail modal heading is in the following format: 
     **Format:** [Application_Name] Feedback
     **Example:** Certification Feedback
1. Verify that the Feedback Detail modal includes the following data elements (refer to mockup): 
    - **User** - Displays "User Email" and the 
    - **Date** - the date the feedback was submitted
   -  **Feedback Comment** - A text box that displays the feedback comment
   - **Status** - A drop down box that defaults to the current status and is editable
1. Verify that the following link is displayed: **_Go Back_**.
1. Verify that the following button is displayed:  **_Create Github Issue_**.

**Comment by shanear** [comment]
This could already be working as intended. Lets verify

**Comment by ghost** [comment]
Not seeing _Tester_:
<img width="922" alt="screen shot 2017-01-27 at 15 32 34" src="https://cloud.githubusercontent.com/assets/18075411/22386596/df090414-e4a5-11e6-9eb9-26dd2fa92e2e.png">
Application name stuck with first word _Caseflow_:
<img width="692" alt="screen shot 2017-01-27 at 15 33 29" src="https://cloud.githubusercontent.com/assets/18075411/22386634/032c8bd6-e4a6-11e6-9132-a1cdf5367abe.png">

**Comment by nikitarockz** [comment]
# Sprint Planning
Decided to remove this issue as it no longer valid.  All is fine.
